In [ ]:
# 폴더비밀번호 ssacnp01

In [1]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
# ([]) 구조를 해야 numpy 사용가능

# np.arrap([1,2,3,]) 초기화 값을 지정하여 배열 생성
# no.zeros() 값을 0을 초기화 하여 배열 생성
# np.ones() 값을 1로 초기화 하여 배열 생성
# np. arange() 수의 순차적인 증감을 이용하여 배열 생성
# np.rand() 랜덤한 숫자로 배열 생성

In [2]:
import numpy as np



array([1, 2, 3])

In [3]:
# np.array(아이템이 나열된 형태의 객체)

list1=[1,2,3]
arr1=np.array(list1)
arr1

array([1, 2, 3])

In [10]:
# np.zeros(배열의 모양)

np.zeros(5) #() 안에 인자는 정수형

np.zeros(25)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,3)) # 행렬로 표현식

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
# np.ones()
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones(5000) #ones은 전부 표시해주지 않음

array([1., 1., 1., ..., 1., 1., 1.])

In [17]:
# np.empty() 의미없는 값으로 채워지기떄문에 조심히 사용
np.empty(5)

array([2.12199579e-314, 6.36598737e-314, 1.06099790e-313, 1.48539705e-313,
       1.90979621e-313])

In [18]:
# np.arange([시작번호],끝번호,[건너뛰는 수])

np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
np.arange(20,30,2) # 숫자위치의 의미 20 : 시작번호/ 30: 끝번호 / 2 :건너뛰는수  /마지막수는 포함x 미만 .range() 랑같다

array([20, 22, 24, 26, 28])

In [21]:
# np.random.randn() 숫자를 랜덤으로 생성

np.random.rand(2,3)

array([[0.24887074, 0.24388993, 0.64505248],
       [0.61714631, 0.43358465, 0.13643671]])

In [ ]:
# rand 균등분포에서 랜덤 추출
# randint 주어진 범위 안에서 랜덤 추출
# rando 표준정규분포에서 랜덤 추출 (평균이 0,표준편차 1)
# normal 정규분포에서 랜덤 추출
# seed 랜덤값 생성기의 시드를 지정
# shuffle 리스트나 배열 순서 섞음

In [25]:
ary =np.random.rand(7,20)
print(ary)

[[0.68061239 0.23405514 0.61370504 0.96557873 0.81296563 0.68611736
  0.30406864 0.51198319 0.03470946 0.74694557 0.29309029 0.26539745
  0.46166406 0.36696838 0.61458663 0.73889299 0.35995022 0.60307337
  0.54352893 0.09367076]
 [0.73109898 0.60117607 0.53882514 0.53728418 0.62910226 0.93552832
  0.61045864 0.97334903 0.83779916 0.12376444 0.17620697 0.52996567
  0.59657773 0.98696087 0.07124501 0.18717103 0.13240075 0.08743681
  0.9042788  0.12908111]
 [0.53736365 0.41239502 0.29456605 0.0890403  0.12056765 0.43820872
  0.16784111 0.56161571 0.86505711 0.83611982 0.67123376 0.52359119
  0.46208096 0.49775213 0.73506445 0.81970299 0.43877003 0.73231355
  0.82906584 0.73861851]
 [0.69309348 0.39518222 0.84017556 0.64703898 0.18556364 0.86917595
  0.78883432 0.4341057  0.74324934 0.95017564 0.28147928 0.00328561
  0.5639237  0.3823957  0.50810633 0.14813033 0.05951846 0.81372558
  0.46855681 0.9997905 ]
 [0.1151634  0.83373979 0.2289088  0.07301931 0.63398811 0.86238145
  0.97751195 0.5

In [26]:
print(np.all(ary>=0.3)) # all 배열의 모든 원소가 조건을 만족하면 true 출력

False


In [27]:
print(np.any(ary >0.7)) # any 배열에 조건을 만족하는 원소가 있으면 true 출력

True


In [33]:
#np.reshape() 기존데이터에 배열 바꾸는거

arr2=np.arange(100)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
arr2.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
arr2.reshape(2,50)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [36]:
arr2.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
arr2.reshape(5,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [38]:
arr2.reshape(20,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [39]:
arr2.reshape(25,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [41]:
arr2.reshape(5,5,4) # arange 소인수분해 각 원소에 곱의값이 aragne 인수값이되어야함

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [42]:
arr2.reshape(2,5,10) # 앞수 덩어리 개수/ 중간 행의 개수/ 마지막 열의 개수

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [44]:
arr=np.arange(10)

In [48]:
#shape 배열의 형태 확인
arr.shape

(10,)

In [46]:
arr.dtype

dtype('int32')

In [47]:
arr.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
x= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21])
print(x.mean())

11.0


In [57]:
print(x.shape)

(21,)


In [65]:
x=np.array([1,3,5])
x

array([1, 3, 5])

In [68]:
x= np.array([1,3,5,7,9,11]).reshape(3,2)
print(x)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [69]:
y= np.ones([3,4]) #ones 배열의 값을 1로 채움
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [76]:
x= np.array([[1,3,5],[2,4,6]])
print(x[1])

[2 4 6]


In [72]:
print(x[1].mean())

4.0


In [73]:
print(x.mean())

3.5


In [74]:
print(x.shape)

(2, 3)


In [99]:
arr= np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [78]:
# 기본인덱스
arr[5]

5

In [79]:
arr[-1]

15

In [80]:
#인덱스 범위
arr[5:8]

array([5, 6, 7])

In [105]:
arr[5] = 100  #추가가 아니라 그위치에 인덱스만 교환
arr

array([  0,   1,   2,   3,   4, 100, 200, 201,   8,   9,  10,  11,  12,
        13,  14,  15])

In [106]:
arr[6:8]=[200,201] # 인덱스 교환에 범위는 [6:8]의미는  6이상 8미만
arr

array([  0,   1,   2,   3,   4, 100, 200, 201,   8,   9,  10,  11,  12,
        13,  14,  15])

In [108]:
arr2= np.arange(16).reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
arr2[1]

array([4, 5, 6, 7])

In [110]:
arr2[1][1]

5

In [111]:
arr2[1][1]=300
arr2

array([[  0,   1,   2,   3],
       [  4, 300,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [113]:
arr2[3][2] =200
arr2

array([[  0,   1,   2,   3],
       [  4, 300,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13, 200,  15]])

In [115]:
#불리언 언덱스
#true, false 의 값을 갖는 자료형

score=[80,90,70,65,85,95,80,75,80]
score_arr=np.array(score)
score_arr


array([80, 90, 70, 65, 85, 95, 80, 75, 80])

In [116]:
score_arr >=90 #90점 이상만 true

array([False,  True, False, False, False,  True, False, False, False])

In [117]:
score_arr[score_arr >=90] #90점 이상인거 결과값 나오게 

array([90, 95])

In [122]:
score_arr[score_arr >=90]=999 #90점이상 999로 치환 인덱스교환이랑 같음
score_arr 

array([ 80, 999,  70,  65,  85, 999,  80,  75,  80])

In [123]:
#메서드 체인 (method chain)  
arr2= np.arange(16).reshape(4,4) #코드라인 줄여서 눈에들어오게하는 방식

In [126]:
a= np.array([10,20,30,40,50,60,70])
print(a)
b= a>50
print(b)

[10 20 30 40 50 60 70]
[False False False False False  True  True]


In [139]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]]) #상항 [[]] 이형식 지키기
print(x)
print(x[1]) # x 배열의 인덱스 1번 내용을 출력
print(x[:1]) # 1차원 배열의 1번 내용을 출력 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[[1 2 3]]


In [132]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x + y)
print(x[:,1] + y[:,1])

[ 5 11 17]


In [146]:
print(x[:,1] + y[:,1]) #[:,0] = 열들의 합 즉 2열 끼리의 합을 출력

[ 5 11 17]


In [145]:
print(x[:,0] + y[:,0]) # [:,0] = 열들의 합 즉 1열 끼리의 합을 출력

[ 3  9 15]


In [135]:
print(x + y)

[[ 3  5  7]
 [ 9 11 13]
 [15 17 19]]


In [156]:
a = np.array([10,20,30,40,50,60,70])
i=[1,3,5] # I=[:4] 같은게 안되는 이유는 값이 지정이안됬기대문에 rang arrage 로 값을 지정을 해줘야함
print(i)
print(a[i]) #인덱싱을 리스트형대로해서 한번에 뽑아오는거

[1, 3, 5]
[20 40 60]


In [171]:
list1 = [[0,10,20],[1,11,21],[2,12,22],[3,13,23],[4,14,24],[5,15,25],[6,16,26],[7,17,27]]
np_ary=np.array(list1)
print(np_ary)
print(np_ary[:,1]) #[:,] ,빼놓치말고 입력해야 다음과같은 결과가 나옴

[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]]
[10 11 12 13 14 15 16 17]


In [179]:
a=np.array([10,20,30,40,50,60,70])
b=np.array(a[1:6:2])
print(b)
print('b:',b)
b[1]=10
print('b:',b)
print('a:',a)
type(b)

[20 40 60]
b: [20 40 60]
b: [20 10 60]
a: [10 20 30 40 50 60 70]


numpy.ndarray

In [210]:
a=np.array([[10,20,30,40,50,60,70],[11,21,31,41,51,61,71],[12,22,32,42,52,62,72]])
b=np.array(a[1:2:3])
print(a)
print(b)
b[0][1]=10 # 2차원에서 바꿔줄떄는 [][]형태로 맞춰서 바꿔줘라 꼭생각하기
print('b:',b)
print('a:',a)

[[10 20 30 40 50 60 70]
 [11 21 31 41 51 61 71]
 [12 22 32 42 52 62 72]]
[[11 21 31 41 51 61 71]]
b: [[11 10 31 41 51 61 71]]
a: [[10 20 30 40 50 60 70]
 [11 21 31 41 51 61 71]
 [12 22 32 42 52 62 72]]


In [184]:
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])

In [185]:
arr+2

array([3, 4, 5, 6])

In [186]:
arr*2

array([2, 4, 6, 8])

In [206]:
# 배열과 배열의 연산을 하기위해서는 배열의 구조가 같아야한다 즉 행렬값이 같아야 적용

arr2=np.arange(1,6)
arr2

arr*arr2 # => 이값은 안되고

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [207]:
arr2=np.arange(2,6)
arr2
arr*arr2 #=> 배열이 같기떄문에 즉 행렬값이 같아야 가능

array([ 2,  6, 12, 20])

In [211]:
list=[1,2,3,4]
list

[1, 2, 3, 4]

In [214]:
list=list*2 # 책방법말고 이방법으로
print(list)

[1, 2, 3, 4, 1, 2, 3, 4]


In [215]:
np.square(arr) #제곱

array([ 1,  4,  9, 16], dtype=int32)

In [216]:
np.sqrt(arr) #제곱근(루트)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [217]:
np.exp(arr) #지수승

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [218]:
np.log(arr) #log

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [224]:
arr= np.arange(1,7)
print(arr)
np.square(arr)

[1 2 3 4 5 6]


array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [225]:
np.add(arr,arr1) #더하기

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

In [226]:
np.sum(arr) #합계

21

In [227]:
np.cumsum(arr) #누적합

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [228]:
np.mean(arr) # 평균

3.5

In [229]:
np.var(arr) #편차

2.9166666666666665

In [230]:
np.std(arr) #표준편차

1.707825127659933

In [231]:
np.min(arr) #최소값

1

In [232]:
np.max(arr) #최대값

6

In [233]:
np.argmin(arr) #최소값의 인덱스

0

In [234]:
np.argmax(arr) #최대값의 인덱스

5

In [235]:
x= np.array([1,2,3])
y= np.array([4,5,6])
z=x*y
print(z)

[ 4 10 18]


In [236]:
x= np.array([1,2,3,4])
y= np.array([7,8,9,10])
z=x*y
print(z)

[ 7 16 27 40]


In [237]:
#Transpose() 변형

arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [238]:
#arr.transpose() 

arr.T # 행과 열 교환

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [239]:
arr3d = np.arange(27).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [240]:
arr3d.transpose() #transpose(2,1,0)와 동일 역순으

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [242]:
arr3d.T #  = arr3d.traonspose() 같음

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [243]:
print(arr3d)
#x=축의 표현이 0 y축의 표현이 1 z축의 표현이 2
arr3d.transpose(1,0,2)  #따라서 y축이 x축으로오고 x축이 y축으로가고 z축이 고정

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]])

In [244]:
#저장

arr=np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [249]:
np.save('array',arr) # 저장하는방법

In [250]:
load_arr=np.load('array.npy') #저장한걸 불러오는 방법
load_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# np.arrange()